import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const contextsRoot = join(appRoot, "contexts");
const outputFile = join(appRoot, "core/shared/generated/contracts.ts");

async function findSchemaFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const location = join(directory, entry.name);
    if (entry.isDirectory()) return findSchemaFiles(location);
    return location.endsWith(".schema.json") ? [location] : [];
  }));
  return files.flat();
}

async function main(): Promise<void> {
  const files = (await findSchemaFiles(contextsRoot)).sort();
  const schemas = await Promise.all(files.map(async (file) => ({ file, schema: JSON.parse(await readFile(file, "utf8")) as Record<string, unknown> })));
  const schemasById = new Map(schemas.flatMap(({ schema }) => typeof schema.$id === "string" ? [[schema.$id, schema] as const] : []));
  const expandReferences = (value: unknown, seen = new Set<string>()): unknown => {
    if (Array.isArray(value)) return value.map((item) => expandReferences(item, seen));
    if (!value || typeof value !== "object") return value;
    const object = value as Record<string, unknown>;
    if (typeof object.$ref === "string" && Object.keys(object).length === 1 && schemasById.has(object.$ref)) {
      if (seen.has(object.$ref)) return object;
      return expandReferences(schemasById.get(object.$ref), new Set([...seen, object.$ref]));
    }
    return Object.fromEntries(Object.entries(object).map(([key, item]) => [key, expandReferences(item, seen)]));
  };
  const declarations = await Promise.all(schemas.map(({ file, schema }) =>
    compile(expandReferences(schema) as object, relative(contextsRoot, file).replaceAll(/[/.\-]/g, "_"), { bannerComment: "" }),
  ));
  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(outputFile, `/* Generated by npm run generate:contracts. Do not edit manually. */\n\n${declarations.join("\n")}`);
  console.log(`Generated ${files.length} contract type declarations.`);
}

void main();
