import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";
import ts from "typescript";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const contextsRoot = join(appRoot, "contexts");
const outputFile = join(appRoot, "core/shared/generated/contracts.ts");
const featureNamesFile = join(appRoot, "core/shared/generated/feature-names.ts");
const frontendModulesFile = join(appRoot, "composition/generated/frontend-modules.ts");

async function findSchemaFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const location = join(directory, entry.name);
      if (entry.isDirectory()) return findSchemaFiles(location);
      return location.endsWith(".schema.json") ? [location] : [];
    }),
  );
  return files.flat();
}

async function main(): Promise<void> {
  const files = (await findSchemaFiles(contextsRoot)).sort();
  const schemas = await Promise.all(
    files.map(async (file) => ({
      file,
      schema: JSON.parse(await readFile(file, "utf8")) as Record<string, unknown>,
    })),
  );
  const schemasById = new Map(
    schemas.flatMap(({ schema }) =>
      typeof schema.$id === "string" ? [[schema.$id, schema] as const] : [],
    ),
  );
  const expandReferences = (value: unknown, seen = new Set<string>()): unknown => {
    if (Array.isArray(value)) return value.map((item) => expandReferences(item, seen));
    if (!value || typeof value !== "object") return value;
    const object = value as Record<string, unknown>;
    if (
      typeof object.$ref === "string" &&
      Object.keys(object).length === 1 &&
      schemasById.has(object.$ref)
    ) {
      if (seen.has(object.$ref)) return object;
      return expandReferences(schemasById.get(object.$ref), new Set([...seen, object.$ref]));
    }
    return Object.fromEntries(
      Object.entries(object).map(([key, item]) => [key, expandReferences(item, seen)]),
    );
  };
  const declarations = await Promise.all(
    schemas.map(({ file, schema }) =>
      compile(
        expandReferences(schema) as object,
        relative(contextsRoot, file).replaceAll(/[/.\-]/g, "_"),
        { bannerComment: "" },
      ),
    ),
  );
  const combined = ts.createSourceFile(
    "contracts.ts",
    declarations.join("\n"),
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const seen = new Map<string, string>();
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const uniqueDeclarations = combined.statements.flatMap((statement) => {
    const named =
      (ts.isInterfaceDeclaration(statement) || ts.isTypeAliasDeclaration(statement)) &&
      statement.name
        ? statement.name.text
        : undefined;
    const rendered = printer.printNode(ts.EmitHint.Unspecified, statement, combined);
    if (!named) return [rendered];
    const previous = seen.get(named);
    if (!previous) {
      seen.set(named, rendered);
      return [rendered];
    }
    if (previous.replaceAll(/\s/g, "") !== rendered.replaceAll(/\s/g, ""))
      throw new Error(`Generated contract name '${named}' has conflicting declarations`);
    return [];
  });
  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(
    outputFile,
    `/* Generated by npm run generate:contracts. Do not edit manually. */\n\n${uniqueDeclarations.join("\n\n")}\n`,
  );
  async function findDefinitions(directory: string): Promise<string[]> {
    const entries = await readdir(directory, { withFileTypes: true });
    return (
      await Promise.all(
        entries.map(async (entry) => {
          const location = join(directory, entry.name);
          if (entry.isDirectory()) return findDefinitions(location);
          return entry.name === "feature.definition.json" ? [location] : [];
        }),
      )
    ).flat();
  }
  const definitionFiles = await findDefinitions(contextsRoot);
  const featureNames = await Promise.all(
    definitionFiles.sort().map(async (file) => {
      const definition = JSON.parse(await readFile(file, "utf8")) as { name: string };
      const property = definition.name
        .split("-")
        .map((part) => part[0]?.toUpperCase() + part.slice(1))
        .join("");
      return `  ${property}: ${JSON.stringify(definition.name)},`;
    }),
  );
  await writeFile(
    featureNamesFile,
    `/* Generated from feature.definition.json files. Do not edit manually. */\nexport const FeatureName = {\n${featureNames.join("\n")}\n} as const;\nexport type FeatureName = (typeof FeatureName)[keyof typeof FeatureName];\n`,
  );
  const frontendModules = await Promise.all(
    definitionFiles.sort().map(async (file) => {
      const definition = JSON.parse(await readFile(file, "utf8")) as {
        name: string;
        frontend: {
          slots: string[];
          eventConsumers?: { name: string; eventType: string; contract: string }[];
        };
      };
      const modulePath = relative(
        dirname(frontendModulesFile),
        join(dirname(file), "frontend", "contribution.js"),
      ).replaceAll("\\", "/");
      return `  {\n    id: ${JSON.stringify(definition.name)},\n    slots: ${JSON.stringify(definition.frontend.slots)} as const,\n    eventConsumers: ${JSON.stringify(definition.frontend.eventConsumers ?? [])} as const,\n    load: () => import(${JSON.stringify(modulePath.startsWith(".") ? modulePath : `./${modulePath}`)}),\n  },`;
    }),
  );
  await mkdir(dirname(frontendModulesFile), { recursive: true });
  await writeFile(
    frontendModulesFile,
    `/* Generated from feature definitions. Do not edit manually. */\nexport const frontendModules = [\n${frontendModules.join("\n")}\n] as const;\n`,
  );
  console.log(`Generated ${files.length} contract type declarations.`);
}

void main();
